-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	brand = { ['loading-logo'] = 'rbxassetid://5492341881' },
	faces = {
		['cartoon-face-angry'] = 'rbxassetid://5584473579',
		['cartoon-face-died'] = 'rbxassetid://5584471203',
		['cartoon-face-sad'] = 'rbxassetid://5584471348',
	},
	money = { ['coins-pile'] = 'rbxassetid://5584627572' },
}