-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	brand = {
		["loading-logo"] = "rbxassetid://5584664400",
	},
	faces = {
		["cartoon-face-angry"] = "rbxassetid://5584664491",
		["cartoon-face-died"] = "rbxassetid://5584664569",
		["cartoon-face-sad"] = "rbxassetid://5584664658",
		["coins-pile"] = "rbxassetid://5584664762",
	},
	money = {
		["coins-pile"] = "rbxassetid://5584627572",
	},
}